name: CI/CD
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

env:
  AWS_DEFAULT_REGION: us-west-2

jobs:
  terraform_validate:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform init
        run: |
          terraform init
      - name: Terraform validate
        run: |
          terraform validate
      - name: Terraform formatting check
        run: |
          terraform fmt -check -recursive
  checkov-job:
    runs-on: ubuntu-latest
    name: Checkov Static Analysis
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          #          check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
          # Skipping:
#          skip_check: # optional: skip a specific check_id. can be comma separated list
#          quiet: true # optional: display only failed checks
#          soft_fail: true # optional: do not return an error code if there are failed checks
#          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
#          output_format: json # optional: the output format, one of: cli, json, junitxml, github_failed_only