---
name: CI/CD
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  terraform_validate:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform init
        run: |
          terraform init
      - name: Terraform validate
        run: |
          terraform validate
      - name: Terraform formatting check
        run: |
          terraform fmt -check -recursive
